spring:
  application:
    name: springsecurityex
  datasource:
    username: root
    password: root@123
    url: jdbc:mariadb://localhost:3306/springsecurityex?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret:
    key: /x8DMvXvVj/iT6CUM4N7yBhYOg/Tmz4xx1ML1WUmSIo=